[GLOBAL]
  Name = test.refineid.irc.local
  AdminInfo1 = RefineID Local Test Agent IRC
  AdminInfo2 = Development & Testing Environment
  AdminEMail = petri.koistinen@refineid.fi
  Info = RefineID Local Test IRC Server
  Listen = 127.0.0.1
  Ports = 6667
  MotdPhrase = [TEST ENV] Welcome to RefineID Local Test IRC Server!
  ServerUID = pk

[LIMITS]
  ConnectRetry = 10
  IdleTimeout = 0
  MaxConnections = 100
  MaxConnectionsIP = 50
  MaxJoins = 50
  MaxNickLength = 20
  PingTimeout = 120
  PongTimeout = 20

[OPTIONS]
  DNS = no
  Ident = no
  NoticeBeforeRegistration = no
  RequireAuthPing = no

[CHANNEL]
  Name = #refineid
  Topic = RefineID Local Test & Experimentation Channel
  Autojoin = yes
